version: "3.8"

services:
  my-service-production:
    container_name: my-service-production
    build:
      target: production
      context: .
      args:
        - PORT=${PORT}
    ports:
      - "${PORT}:${PORT}"

  my-service-dev:
    container_name: my-service-dev
    restart: unless-stopped
    build:
      target: dev
      context: .
      args:
        - PORT=${PORT}
    ports:
      - "${PORT}:${PORT}"
      - "9229:9229"
    volumes:
      - .:/project
      - exclude:/project/node_modules/

volumes:
  exclude:
