version: '3.5'
services:
  my-service-production:
    container_name: my-service-production
    build:
      target: production
      context: .
      dockerfile: Dockerfile
      args:
        - PORT = ${PORT}
    ports:
      - ${PORT}:${PORT}
    env_file: .env
  my-service-dev:
    container_name: my-service-dev
    restart: always
    build:
      target: dev
      context: .
      dockerfile: Dockerfile
      args:
        - PORT = ${PORT}
    ports:
      - ${PORT}:${PORT}
      - "9229:9229"
    env_file: .env
    volumes:
      - .:/project
      - exclude:/project/node_modules/
volumes:
  exclude:
