---
name: 'Assign me'

on:
  pull_request:

jobs:
  set_assignee:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        if: github.actor != 'dependabot[bot]'
        with:
          script: |
            github.rest.issues.addAssignees({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              assignees: [context.actor],
            })
