name: '💅 Lint'

on:
  push:

jobs:
  lint-dotenv:
    name: Lint dotenv
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dotenv
        run: curl -sSfL https://git.io/JLbXn | sh -s -- -b usr/local/bin v3.3.0
      - name: Run dotenv
        run: usr/local/bin/dotenv-linter

  lint-dockerfile:
    name: Lint dockerfile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hadolint/hadolint-action@v3.1.0
        id: hadolint
        with:
          dockerfile: Dockerfile
      - name: Build dockerfile
        run: docker build . -t service

  lint-github-actions:
    name: Lint GitHub Actions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download actionlint
        id: get_actionlint
        run: bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash) 1.6.26
        shell: bash
      - name: Check workflow files
        run: ${{ steps.get_actionlint.outputs.executable }} -color
        shell: bash

  lint-yaml:
    name: Lint yaml
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install yamllint
        run: pip install yamllint
      - name: Lint YAML files
        run: yamllint .

  lint-typos:
    name: Lint typos
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛬
        uses: actions/checkout@v4
      - name: 🙊 Run code spell checker to check typos
        uses: crate-ci/typos@v1.27.3
