name: '🐢 Node'

on:
  push:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛬
        uses: actions/checkout@v4
      - name: Setup Node ⚙️
        uses: ./.github/actions/setup-node
      - name: Build typescript 📦
        run: pnpm build && find dist/main.js
      - name: Lint code 💅
        run: pnpm lint
      - name: Run tests ✅
        run: pnpm test
