name: 'Node'

on:
  push:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛬
        uses: actions/checkout@v4
      - name: Setup Node ⚙️
        uses: ./.github/actions/setup-node
      - name: Build typescript 📦
        run: npm run build && find dist/main.js
      - name: Lint code 💅
        run: npm run lint
      - name: Run tests ✅
        run: npm run test
