name: 'PR Scope label'

on:
  pull_request_target:
    types: [opened, synchronize, reopened]

jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v5
        with:
          configuration-path: .github/pr-scope-labeler.yml
          sync-labels: true
